### ISSUE TITLE
ChatsLoader Problems

### ISSUE THREAD

**Issue by emmanuelcolina14** [p-vorobyev/spring-boot-starter-telegram#29]
Hi, i have a problem when compile the project..

![image](https://github.com/user-attachments/assets/43afb3f3-fa4f-425b-b0ac-036be5023432)

**Comment by p-vorobyev** [comment]
Hi, @emmanuelcolina14! The root cause is listed above in your log with the ERROR level - `no libcrypto-x64 in java.library.path...`. You need to specify JVM property `-Djava.library.path=<path_to_shared_library>` with path to native libraries when running the application(in your case for Windows). You can find precompiled libraries in the latest release page. It's step 4 of the installation [instructions](https://github.com/p-vorobyev/spring-boot-starter-telegram?tab=readme-ov-file#installation).
