### ISSUE TITLE
How to repeatedly send verification codes

### ISSUE THREAD

**Issue by zcxgsq** [p-vorobyev/spring-boot-starter-telegram#32]
目前遇到无法重复发送验证码的问题new TdApi.ResendPhoneNumberConfirmationCode()与new TdApi.ResendAuthenticationCode()都不起作用

**Comment by p-vorobyev** [comment]
Hi, @zcxgsq ! A verification code is sent the first time you login, and you don't need to resend it on the next startups.

If you want to resend the authentication code to authorize your client because of you failed to verify it at the first time, you can do one of these two steps:
1. Stop the app, clear the database directory and start the app again. Or just call `LogOut` [function](https://p-vorobyev.github.io/javadoc_spring-boot-starter-telegram/org/drinkless/tdlib/TdApi.LogOut.html) to destroy all local data and restart the app.
2. If you want to resend the code on the running app without deleting local data you can try to call `telegramClient.sendAsync(new TdApi.ResendAuthenticationCode());` [function](https://p-vorobyev.github.io/javadoc_spring-boot-starter-telegram/org/drinkless/tdlib/TdApi.ResendAuthenticationCode.html). But it has limitations on using(see the documentation at the link). 

From my point of view, the first option is the easiest one.

**Comment by zcxgsq** [comment]
Thank you, I have already resolved it
